Add flash-router with dummy resource
brave-ruby-squad/rails-api-skeleton pull request #3
Opened 2018-03-21 13:54 UTC by andrewr224

2018-03-21 13:55 UTC, andrewr224 commented on config/router.rb
> +    "Routes::#{route_name.to_s.camelize}".constantize
**We need to:**

1. think how to receive the scope which contains specify that has been called;
2. build class name with respective namespacing

2018-03-22 11:14 UTC, ailecksandr requested changes

2018-03-22 11:14 UTC, ailecksandr commented on config/initializers/scope.rb
> +        def quack
:frog:

2018-03-22 11:20 UTC, ailecksandr approved these changes

2018-03-22 11:20 UTC, merged